.TH HORSE 1 "October 2025" "horse 0.1.0" "User Commands"
.SH NAME
horse \- display an animated ASCII art carousel of horses
.SH SYNOPSIS
.B horse
.SH DESCRIPTION
.B horse
displays a continuously looping carousel animation of five different ASCII art horses in your terminal. The animation cycles through different artistic representations of horses, creating a mesmerizing display.

Press Ctrl+C to exit the animation.

.nf
                                     _ _
                                   .' ` `.
                                  /  /(`)\\
                                 | _/a  a(|
                                 |(G   ) ||
                                 /\\ '--`/|
                                /  )|'-;' |
                               /  / /  :  \\
                               \\,-\\(`._/`-.)
                               /   `      ,`,
                              Y   Y       \\ ]
                              |   |        \\|
                              |.--;\\___/  _/;
                      .-._    '.   `.__   ]  `.__        _.-,
                       `'-::-...`-.._  \\________ \\_...-::-'`
           _....___         `'';;---.///-------=//-'''`
    ,.._.-;;       '''--...--;'     -.     \\
  .'.=.'**;;                          `.  [ Y
 /   /*****;;                           \\]  J
Y / Y*****;;;;                           Y   L
| | |****;;  ;;;                         |   L
| | |***;;     ;;                        A  J
|   I**;;       ;;                      /I\\ /
|    \\*;;       ;;,           \\        ( |]/|
J     \\'        /;;;,         /        -tI/ |
 L     )       /   /'-------'J           `'-:.
 J   .'      ,'  ,' ,     \\   `'-.__          \\
  \\ T      ,'  ,'   )\\    /|        ';'---7   /
   \\|    ,'L  Y...-' / _.' /         \\   /   /
    J   Y  |  J    .'-'   /         ,--.(   /
     L  |  J   L -'     .'         /  |    /\\
     |  J.  L  J     .-;.-/       |    \\ .' /    -Sgt Pinback-
     J   L`-J   L____,.-'`        |  _.-'   |      after sk
      L  J   L  J                  ``  J    |
      J   L  |   L                     J    |
       L  J  L    \\                    L    \\
       |   L  ) _.'\\                    ) _.'\\
       L    \\('`    \\                  ('`    \\
        ) _.'\\`-....'                   `-....'
       ('`    \\
        `-.___/   sk
.fi

.SH EXAMPLES
To run the animation:
.RS
.B horse
.RE

.SH EXIT STATUS
The program exits with status 0 when terminated with Ctrl+C.

.SH AUTHORS
ASCII art courtesy of https://www.asciiart.eu/mythology/centaurs

.SH SEE ALSO
.BR cowsay (1),
.BR fortune (1)
