name: Build Homebrew Bottles

on:
  push:
    tags:
      - "v*"

jobs:
  build-bottles:
    name: Build bottle for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Extract version from tag
        id: version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build release binary
        run: cargo build --release

      - name: Detect architecture and OS
        id: detect
        run: |
          ARCH=$(uname -m)
          if [ "$ARCH" = "arm64" ]; then
            BOTTLE_ARCH="arm64"
          elif [ "$ARCH" = "x86_64" ]; then
            BOTTLE_ARCH="x86_64"
          fi

          # Map runner OS to Homebrew bottle naming
          case "${{ matrix.os }}" in
            macos-13)
              BOTTLE_OS="ventura"
              ;;
            macos-14)
              BOTTLE_OS="sonoma"
              ;;
            macos-15)
              BOTTLE_OS="sequoia"
              ;;
            macos-26)
              BOTTLE_OS="tahoe"
              ;;
          esac

          echo "arch=$BOTTLE_ARCH" >> $GITHUB_OUTPUT
          echo "os=$BOTTLE_OS" >> $GITHUB_OUTPUT

      - name: Create bottle
        id: bottle
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          ARCH="${{ steps.detect.outputs.arch }}"
          OS="${{ steps.detect.outputs.os }}"
          BOTTLE_NAME="horse-${VERSION}.${ARCH}_${OS}.bottle.tar.gz"

          # Create Cellar directory structure
          BOTTLE_DIR="bottle_tmp"
          CELLAR_PATH="${BOTTLE_DIR}/horse/${VERSION}"
          mkdir -p "${CELLAR_PATH}/bin"
          mkdir -p "${CELLAR_PATH}/share/man/man1"

          # Copy binary
          cp target/release/horse "${CELLAR_PATH}/bin/"

          # Copy man page
          cp man/horse.1 "${CELLAR_PATH}/share/man/man1/"

          # Create tarball
          cd "${BOTTLE_DIR}"
          tar -czf "../${BOTTLE_NAME}" horse
          cd ..

          # Calculate SHA256
          BOTTLE_SHA256=$(shasum -a 256 "${BOTTLE_NAME}" | cut -d' ' -f1)

          echo "name=${BOTTLE_NAME}" >> $GITHUB_OUTPUT
          echo "sha256=${BOTTLE_SHA256}" >> $GITHUB_OUTPUT

          echo "Created bottle: ${BOTTLE_NAME}"
          echo "SHA256: ${BOTTLE_SHA256}"

      - name: Upload bottle to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.ref_name }} \
            ${{ steps.bottle.outputs.name }} \
            --repo ${{ github.repository }} \
            --clobber
