name: Release

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Homebrew formula
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the release tag
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}

          # Download the release tarball to calculate SHA256
          TARBALL_URL="https://github.com/notjosh/manhorse/archive/refs/tags/${TAG}.tar.gz"
          curl -L "$TARBALL_URL" -o source.tar.gz
          SHA256=$(shasum -a 256 source.tar.gz | awk '{print $1}')

          # Create Formula directory if it doesn't exist
          mkdir -p Formula

          # Generate the formula
          cat > Formula/horse.rb <<EOF
          class Horse < Formula
            desc "Display an animated ASCII art carousel of horses"
            homepage "https://github.com/notjosh/manhorse"
            url "${TARBALL_URL}"
            sha256 "${SHA256}"
            license "MIT"

            depends_on "rust" => :build

            def install
              system "cargo", "install", *std_cargo_args
              man1.install "man/horse.1"
            end

            test do
              assert_predicate bin/"horse", :exist?
            end
          end
          EOF

          # Commit and push
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/horse.rb
          git commit -m "Update horse formula to ${VERSION}"
          git push
